version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: uri-backend
    container_name: uri-backend
    depends_on:
      - postgres
      - redis
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_CLICKHOUSE_URL: jdbc:clickhouse://clickhouse:8123/
      SPRING_CLICKHOUSE_USERNAME: ${CLICKHOUSE_USER}
      SPRING_CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: 'redis:latest'
    container_name: redis-cache
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "6380:6379"
    networks:
      - backend

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-db
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
    ports:
      - "8124:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - "./src/main/resources/db/migration/clickhouse:/docker-entrypoint-initdb.d"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
  clickhouse-data:
