
spring:
  application:
    name: uri

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        generate-ddl: true
        hbm2ddl:
          auto: update
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        boot:
          allow_jdbc_metadata_access: false

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      repositories.enabled: false


clickhouse:
  url: ${SPRING_CLICKHOUSE_URL}
  username: ${SPRING_CLICKHOUSE_USERNAME}
  password: ${SPRING_CLICKHOUSE_PASSWORD}
  driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

jwt:
  secret:
    access-expiration: ACCESS_TOKEN_EXPIRATION_TIME_IN_MILLISECONDS
    expiration: EXPIRATION_TIME_IN_MILLISECONDS
    refresh-expiration: REFRESH_TOKEN_EXPIRATION_TIME_IN_MILLISECONDS
    access-key: ACCESS_KEY_SECRET
    refresh-key: REFRESH_KEY_SECRET

cookie:
  token:
    expiration: COOKIE_EXPIRATION_TIME_IN_SECONDS

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging.level.org.springframework:
  web: DEBUG
  data.redis: DEBUG